version: '3'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginxcon
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_vol:/var/www/html
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadbcon
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception
  wordpress:
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    container_name: wordpresscon
    restart: always
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress_vol:/var/www/html
volumes:
  mariadb_vol:
    name: mariadb_vol
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ynuiga/data/mariadb_vol
  wordpress_vol:
    name: wordpress_vol
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ynuiga/data/wordpress_vol
networks:
  inception:
    driver: bridge
