version: '3'
services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginxcon
    env_file: .env
    ports:
      - 443:443
    networks:
      - inception
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadbcon
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - mariadbvol:/var/lib/mysql
    networks:
      - inception
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    depens_on: mariadb
    container_name: wordpresscon
    env_file: .env
    # ports:
    #   - 
    networks:
      - inception
volumes:
  mariadbvol:
    # name: mariadb
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: /home/ynuiga/data/mariadb
  wordpressvol:
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: /home/ynuiga/data/wordpress
networks:
  inception:
    driver: bridge
